### ISSUE TITLE
EE3 Compatibility?

### ISSUE THREAD

**Issue by aarondmills** [EllisLab/Char-Limit#7]
Is this going to be V3 compatible?

**Comment by robinsowell** [comment]
It was missed inadvertently and really should have been done in the initial round of updates.

Thanks for the heads up, I'll get on it!

**Comment by carolinecblaker** [comment]
Hi Robin - what's the status here?

**Comment by robinsowell** [comment]
Sorry about that, Caroline!  The master branch is now v3 compatible.  You can [download](https://github.com/EllisLab/char-limit) it now.

Let me know if you have any trouble!
